#!/usr/bin/env bash

echo "Change Theme"
echo "=== Anime Theme ==="
echo "1. Persona"
echo "2. Katou Megumi"
echo "3. Koi Yuki"
echo "4. Oreki Houtarou"
echo "=== Normal Theme ==="
echo "5. Frosted"
echo " "
echo "Choose theme index : "
read choose

case $choose in
    1)
    rm ~/.config/i3/theme/now && echo "persona" >> ~/.config/i3/theme/now
    echo "Theme changed to : Persona"
    ;;
    2)
    rm ~/.config/i3/theme/now && echo "megumi" >> ~/.config/i3/theme/now
    echo "Theme changed to : Katou Megumi"
    ;;
    3)
    rm ~/.config/i3/theme/now && echo "koiyuki" >> ~/.config/i3/theme/now
    echo "Theme changed to : Koi Yuki"
    ;;
    4)
    rm ~/.config/i3/theme/now && echo "oreki" >> ~/.config/i3/theme/now
    echo "Theme changed to : Oreki Houtarou"
    ;;
    5)
    rm ~/.config/i3/theme/now && echo "frosted" >> ~/.config/i3/theme/now
    echo "Theme changed to : Frosted"
    ;;
    *)
    echo "Input error"
    ;;
esac

~/.config/i3/kill-ui &> /dev/null
~/.config/i3/startup &> /dev/null
