#!/usr/bin/env bash

theme="$(cat ~/.config/i3/theme/now)"

megumi() {
    # Dunst
    dunst -config ~/.config/dunst/dunstrc-left &
    # Wallpaper
    feh --bg-fill ~/.wallpaper/kato.png
    # GTK, rofi, color theme
    ~/.config/i3/theme/megumi/megumi-theme
    # Panel
    tint2 -c ~/.config/tint2/megumi-i3.tint2rc &
    # Terminal Color Scheme
    xrdb ~/.config/i3/theme/megumi/.Xresources

}

persona() {
    # Dunst
    dunst -config ~/.config/dunst/dunstrc-dark-left &
    # Wallpaper
    feh --bg-fill ~/.wallpaper/p3.png
    # GTK, rofi, color theme
    ~/.config/i3/theme/persona/persona-theme
    # Panel
    tint2 -c ~/.config/tint2/persona-i3.tint2rc &
    # Terminal Color Scheme
    xrdb ~/.config/i3/theme/persona/.Xresources

}
koiyuki() {
    # Dunst
    dunst -config ~/.config/dunst/dunstrc-left &
    # Wallpaper
    feh --bg-fill ~/.wallpaper/koi_yuki.jpg
    # GTK, rofi, color theme
    ~/.config/i3/theme/koiyuki/koiyuki-theme
    # Panel
    tint2 -c ~/.config/tint2/koiyuki-i3.tint2rc &
    # Terminal Color Scheme
    xrdb ~/.config/i3/theme/koiyuki/.Xresources
}

oreki() {
    # Dunst
    dunst -config ~/.config/dunst/dunstrc-dark-left &
    # Wallpaper
    feh --bg-fill ~/.wallpaper/oreki.jpg
    # GTK, rofi, color theme
    ~/.config/i3/theme/oreki/oreki-theme
    # Panel
    tint2 -c ~/.config/tint2/oreki-i3.tint2rc &
    # Terminal Color Scheme
    xrdb ~/.config/i3/theme/oreki/.Xresources
}

frosted() {
    # Dunst
    dunst -config ~/.config/dunst/dunstrc-left &
    # Wallpaper
    feh --bg-fill ~/.wallpaper/frosted.jpg
    # GTK, rofi, color theme
    ~/.config/i3/theme/frosted/frosted-theme
    # Panel
    tint2 -c ~/.config/tint2/frosted-i3.tint2rc &
    # Terminal Color Scheme
    xrdb ~/.config/i3/theme/frosted/.Xresources
}

"$theme"
exit

