#!/usr/bin/env bash

# GTK
sed -i '5s_gtk-theme-name=.*_gtk-theme-name="ZorinBlue-Light"_' ~/.gtkrc-2.0
sed -i '10s_gtk-theme-name=.*_gtk-theme-name=ZorinBlue-Light_' ~/.config/gtk-3.0/settings.ini

# Icon
sed -i '6s_gtk-icon-theme-name=.*_gtk-icon-theme-name="oomox-frosted"_' ~/.gtkrc-2.0
sed -i '8s_gtk-icon-theme-name=.*_gtk-icon-theme-name=oomox-frosted_' ~/.config/gtk-3.0/settings.ini
sed -i '4s\icon_theme=.*\icon_theme=oomox-frosted\' ~/.config/qt5ct/qt5ct.conf

# Rofi
sed -i '5s_colorschemes/.*.rasi_colorschemes/fullscreen.rasi_' ~/.config/rofi/themes/shared/settings.rasi
sed -i '5s_colorschemes/.*.rasi_colorschemes/sidebar.rasi_' ~/.config/rofi/themes/sidebar/colors.rasi
